In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import dataset

In [2]:
data = pd.read_csv("data/train.csv")

In [3]:
data.head()

ID   timestamp item corporation location  supply(kg)  \
0  TG_A_J_20190101  2019-01-01   TG           A        J         0.0   
1  TG_A_J_20190102  2019-01-02   TG           A        J         0.0   
2  TG_A_J_20190103  2019-01-03   TG           A        J     60601.0   
3  TG_A_J_20190104  2019-01-04   TG           A        J     25000.0   
4  TG_A_J_20190105  2019-01-05   TG           A        J     32352.0   

   price(원/kg)  
0          0.0  
1          0.0  
2       1728.0  
3       1408.0  
4       1250.0

## check categories for each col

In [8]:
item_uniq = data['item'].unique()
corp_uniq = data['corporation'].unique()
loc_uniq = data['location'].unique()

print(item_uniq)
print(corp_uniq)
print(loc_uniq)

### 품목 : ['TG' 'CR' 'CB' 'RD' 'BC']
### 회사 : ['A' 'B' 'C' 'D' 'E' 'F']
### 지역 : ['J' 'S']


['TG' 'CR' 'CB' 'RD' 'BC']
['A' 'B' 'C' 'D' 'E' 'F']
['J' 'S']


In [19]:
data.groupby('item')['corporation'].unique()

item
BC    [A, B, C, D, E]
CB       [A, D, E, F]
CR    [A, B, C, D, E]
RD    [A, C, D, E, F]
TG    [A, B, C, D, E]
Name: corporation, dtype: object

In [20]:
data.groupby('item')['location'].unique()

item
BC    [J, S]
CB    [J, S]
CR    [J, S]
RD    [J, S]
TG    [J, S]
Name: location, dtype: object

In [4]:
ID_split = data['ID'].str.split('_')
# print(ID_split)

code = []
for l in ID_split:
    code.append(f"{l[0]}_{l[1]}_{l[2]}")

unique_code = set(code)
print(set(code))


{'TG_C_S', 'TG_B_J', 'CR_A_J', 'CB_A_S', 'BC_C_S', 'TG_E_S', 'CR_C_J', 'RD_E_S', 'TG_B_S', 'RD_D_S', 'BC_E_J', 'BC_E_S', 'BC_A_J', 'CR_D_J', 'CB_D_J', 'BC_B_J', 'RD_F_J', 'CB_E_J', 'CR_B_J', 'CB_F_J', 'TG_E_J', 'RD_A_J', 'TG_D_S', 'BC_A_S', 'BC_D_J', 'RD_C_S', 'RD_E_J', 'CB_A_J', 'CR_E_J', 'RD_A_S', 'TG_A_S', 'TG_D_J', 'BC_C_J', 'TG_A_J', 'BC_B_S', 'TG_C_J', 'CR_D_S', 'RD_D_J', 'CR_E_S'}


## dataset 분할
### df_list에 {data_item_corp_loc}으로 저장 

In [107]:
unique_code = ['BC_C_J', 'TG_B_J', 'CR_B_J', 'RD_E_S', 'BC_A_J', 'CB_F_J', 'RD_D_J', 'TG_A_S', 'BC_E_S', 'CR_D_J', 'BC_A_S', 'BC_B_S', 'TG_E_J', 'CR_E_S', 'RD_F_J', 'BC_E_J', 'TG_A_J', 'CR_C_J', 'CR_D_S', 'TG_C_J', 'CB_A_S', 'TG_D_J', 'CR_E_J', 'RD_C_S', 'BC_C_S', 'CB_E_J', 'RD_E_J', 'BC_D_J', 'CR_A_J', 'TG_E_S', 'TG_C_S', 'TG_D_S', 'RD_A_S', 'RD_A_J', 'RD_D_S', 'TG_B_S', 'CB_D_J', 'CB_A_J', 'BC_B_J']

In [5]:
df_list = {}
for code in unique_code:
    code_parts = code.split('_')
    code_item, code_corporation, code_location = code_parts[0], code_parts[1], code_parts[2]
    
    condition = (data['item'] == code_item) & (data['corporation'] == code_corporation) & (data['location'] == code_location)
    
    df_list[f"data_{code}"] = data[condition]

print(df_list.keys())


dict_keys(['data_TG_C_S', 'data_TG_B_J', 'data_CR_A_J', 'data_CB_A_S', 'data_BC_C_S', 'data_TG_E_S', 'data_CR_C_J', 'data_RD_E_S', 'data_TG_B_S', 'data_RD_D_S', 'data_BC_E_J', 'data_BC_E_S', 'data_BC_A_J', 'data_CR_D_J', 'data_CB_D_J', 'data_BC_B_J', 'data_RD_F_J', 'data_CB_E_J', 'data_CR_B_J', 'data_CB_F_J', 'data_TG_E_J', 'data_RD_A_J', 'data_TG_D_S', 'data_BC_A_S', 'data_BC_D_J', 'data_RD_C_S', 'data_RD_E_J', 'data_CB_A_J', 'data_CR_E_J', 'data_RD_A_S', 'data_TG_A_S', 'data_TG_D_J', 'data_BC_C_J', 'data_TG_A_J', 'data_BC_B_S', 'data_TG_C_J', 'data_CR_D_S', 'data_RD_D_J', 'data_CR_E_S'])


In [7]:
df_list['data_RD_C_S']

ID   timestamp item corporation location  supply(kg)  \
35029  RD_C_S_20190101  2019-01-01   RD           C        S         0.0   
35030  RD_C_S_20190102  2019-01-02   RD           C        S         0.0   
35031  RD_C_S_20190103  2019-01-03   RD           C        S         0.0   
35032  RD_C_S_20190104  2019-01-04   RD           C        S         0.0   
35033  RD_C_S_20190105  2019-01-05   RD           C        S         0.0   
...                ...         ...  ...         ...      ...         ...   
36547  RD_C_S_20230227  2023-02-27   RD           C        S         0.0   
36548  RD_C_S_20230228  2023-02-28   RD           C        S         0.0   
36549  RD_C_S_20230301  2023-03-01   RD           C        S         0.0   
36550  RD_C_S_20230302  2023-03-02   RD           C        S         0.0   
36551  RD_C_S_20230303  2023-03-03   RD           C        S         0.0   

       price(원/kg)  
35029          0.0  
35030          0.0  
35031          0.0  
35032          0.0  
35033          0.0  
...            ...  
36547          0.0  
36548          0.0  
36549          0.0  
36550          0.0  
36551          0.0  

[1523 rows x 7 columns]

In [15]:
def standardization(train_df, test_df, not_col, target):
    train_df_ = train_df.copy()
    print(train_df)
    test_df_ = test_df.copy()
    print(test_df)
    col =  [col for col in list(train_df.columns) if col not in [not_col]]
    mean_list = []
    std_list = []
    for x in col:
        mean, std = train_df_.agg(["mean", "std"]).loc[:,x]
        mean_list.append(mean)
        std_list.append(std)
        train_df_.loc[:, x] = (train_df_[x] - mean) / std
        test_df_.loc[:, x] = (test_df_[x] - mean) / std
    return train_df_, test_df_, mean_list[col.index(target)], std_list[col.index(target)]

TypeError: Could not convert string 'BC_A_J_20190101BC_A_J_20190102BC_A_J_20190103BC_A_J_20190104BC_A_J_20190105BC_A_J_20190106BC_A_J_20190107BC_A_J_20190108BC_A_J_20190109BC_A_J_20190110BC_A_J_20190111BC_A_J_20190112BC_A_J_20190113BC_A_J_20190114BC_A_J_20190115BC_A_J_20190116BC_A_J_20190117BC_A_J_20190118BC_A_J_20190119BC_A_J_20190120BC_A_J_20190121BC_A_J_20190122BC_A_J_20190123BC_A_J_20190124BC_A_J_20190125BC_A_J_20190126BC_A_J_20190127BC_A_J_20190128BC_A_J_20190129BC_A_J_20190130BC_A_J_20190131BC_A_J_20190201BC_A_J_20190202BC_A_J_20190203BC_A_J_20190204BC_A_J_20190205BC_A_J_20190206BC_A_J_20190207BC_A_J_20190208BC_A_J_20190209BC_A_J_20190210BC_A_J_20190211BC_A_J_20190212BC_A_J_20190213BC_A_J_20190214BC_A_J_20190215BC_A_J_20190216BC_A_J_20190217BC_A_J_20190218BC_A_J_20190219BC_A_J_20190220BC_A_J_20190221BC_A_J_20190222BC_A_J_20190223BC_A_J_20190224BC_A_J_20190225BC_A_J_20190226BC_A_J_20190227BC_A_J_20190228BC_A_J_20190301BC_A_J_20190302BC_A_J_20190303BC_A_J_20190304BC_A_J_20190305BC_A_J_20190306BC_A_J_20190307BC_A_J_20190308BC_A_J_20190309BC_A_J_20190310BC_A_J_20190311BC_A_J_20190312BC_A_J_20190313BC_A_J_20190314BC_A_J_20190315BC_A_J_20190316BC_A_J_20190317BC_A_J_20190318BC_A_J_20190319BC_A_J_20190320BC_A_J_20190321BC_A_J_20190322BC_A_J_20190323BC_A_J_20190324BC_A_J_20190325BC_A_J_20190326BC_A_J_20190327BC_A_J_20190328BC_A_J_20190329BC_A_J_20190330BC_A_J_20190331BC_A_J_20190401BC_A_J_20190402BC_A_J_20190403BC_A_J_20190404BC_A_J_20190405BC_A_J_20190406BC_A_J_20190407BC_A_J_20190408BC_A_J_20190409BC_A_J_20190410BC_A_J_20190411BC_A_J_20190412BC_A_J_20190413BC_A_J_20190414BC_A_J_20190415BC_A_J_20190416BC_A_J_20190417BC_A_J_20190418BC_A_J_20190419BC_A_J_20190420BC_A_J_20190421BC_A_J_20190422BC_A_J_20190423BC_A_J_20190424BC_A_J_20190425BC_A_J_20190426BC_A_J_20190427BC_A_J_20190428BC_A_J_20190429BC_A_J_20190430BC_A_J_20190501BC_A_J_20190502BC_A_J_20190503BC_A_J_20190504BC_A_J_20190505BC_A_J_20190506BC_A_J_20190507BC_A_J_20190508BC_A_J_20190509BC_A_J_20190510BC_A_J_20190511BC_A_J_20190512BC_A_J_20190513BC_A_J_20190514BC_A_J_20190515BC_A_J_20190516BC_A_J_20190517BC_A_J_20190518BC_A_J_20190519BC_A_J_20190520BC_A_J_20190521BC_A_J_20190522BC_A_J_20190523BC_A_J_20190524BC_A_J_20190525BC_A_J_20190526BC_A_J_20190527BC_A_J_20190528BC_A_J_20190529BC_A_J_20190530BC_A_J_20190531BC_A_J_20190601BC_A_J_20190602BC_A_J_20190603BC_A_J_20190604BC_A_J_20190605BC_A_J_20190606BC_A_J_20190607BC_A_J_20190608BC_A_J_20190609BC_A_J_20190610BC_A_J_20190611BC_A_J_20190612BC_A_J_20190613BC_A_J_20190614BC_A_J_20190615BC_A_J_20190616BC_A_J_20190617BC_A_J_20190618BC_A_J_20190619BC_A_J_20190620BC_A_J_20190621BC_A_J_20190622BC_A_J_20190623BC_A_J_20190624BC_A_J_20190625BC_A_J_20190626BC_A_J_20190627BC_A_J_20190628BC_A_J_20190629BC_A_J_20190630BC_A_J_20190701BC_A_J_20190702BC_A_J_20190703BC_A_J_20190704BC_A_J_20190705BC_A_J_20190706BC_A_J_20190707BC_A_J_20190708BC_A_J_20190709BC_A_J_20190710BC_A_J_20190711BC_A_J_20190712BC_A_J_20190713BC_A_J_20190714BC_A_J_20190715BC_A_J_20190716BC_A_J_20190717BC_A_J_20190718BC_A_J_20190719BC_A_J_20190720BC_A_J_20190721BC_A_J_20190722BC_A_J_20190723BC_A_J_20190724BC_A_J_20190725BC_A_J_20190726BC_A_J_20190727BC_A_J_20190728BC_A_J_20190729BC_A_J_20190730BC_A_J_20190731BC_A_J_20190801BC_A_J_20190802BC_A_J_20190803BC_A_J_20190804BC_A_J_20190805BC_A_J_20190806BC_A_J_20190807BC_A_J_20190808BC_A_J_20190809BC_A_J_20190810BC_A_J_20190811BC_A_J_20190812BC_A_J_20190813BC_A_J_20190814BC_A_J_20190815BC_A_J_20190816BC_A_J_20190817BC_A_J_20190818BC_A_J_20190819BC_A_J_20190820BC_A_J_20190821BC_A_J_20190822BC_A_J_20190823BC_A_J_20190824BC_A_J_20190825BC_A_J_20190826BC_A_J_20190827BC_A_J_20190828BC_A_J_20190829BC_A_J_20190830BC_A_J_20190831BC_A_J_20190901BC_A_J_20190902BC_A_J_20190903BC_A_J_20190904BC_A_J_20190905BC_A_J_20190906BC_A_J_20190907BC_A_J_20190908BC_A_J_20190909BC_A_J_20190910BC_A_J_20190911BC_A_J_20190912BC_A_J_20190913BC_A_J_20190914BC_A_J_20190915BC_A_J_20190916BC_A_J_20190917BC_A_J_20190918BC_A_J_20190919BC_A_J_20190920BC_A_J_20190921BC_A_J_20190922BC_A_J_20190923BC_A_J_20190924BC_A_J_20190925BC_A_J_20190926BC_A_J_20190927BC_A_J_20190928BC_A_J_20190929BC_A_J_20190930BC_A_J_20191001BC_A_J_20191002BC_A_J_20191003BC_A_J_20191004BC_A_J_20191005BC_A_J_20191006BC_A_J_20191007BC_A_J_20191008BC_A_J_20191009BC_A_J_20191010BC_A_J_20191011BC_A_J_20191012BC_A_J_20191013BC_A_J_20191014BC_A_J_20191015BC_A_J_20191016BC_A_J_20191017BC_A_J_20191018BC_A_J_20191019BC_A_J_20191020BC_A_J_20191021BC_A_J_20191022BC_A_J_20191023BC_A_J_20191024BC_A_J_20191025BC_A_J_20191026BC_A_J_20191027BC_A_J_20191028BC_A_J_20191029BC_A_J_20191030BC_A_J_20191031BC_A_J_20191101BC_A_J_20191102BC_A_J_20191103BC_A_J_20191104BC_A_J_20191105BC_A_J_20191106BC_A_J_20191107BC_A_J_20191108BC_A_J_20191109BC_A_J_20191110BC_A_J_20191111BC_A_J_20191112BC_A_J_20191113BC_A_J_20191114BC_A_J_20191115BC_A_J_20191116BC_A_J_20191117BC_A_J_20191118BC_A_J_20191119BC_A_J_20191120BC_A_J_20191121BC_A_J_20191122BC_A_J_20191123BC_A_J_20191124BC_A_J_20191125BC_A_J_20191126BC_A_J_20191127BC_A_J_20191128BC_A_J_20191129BC_A_J_20191130BC_A_J_20191201BC_A_J_20191202BC_A_J_20191203BC_A_J_20191204BC_A_J_20191205BC_A_J_20191206BC_A_J_20191207BC_A_J_20191208BC_A_J_20191209BC_A_J_20191210BC_A_J_20191211BC_A_J_20191212BC_A_J_20191213BC_A_J_20191214BC_A_J_20191215BC_A_J_20191216BC_A_J_20191217BC_A_J_20191218BC_A_J_20191219BC_A_J_20191220BC_A_J_20191221BC_A_J_20191222BC_A_J_20191223BC_A_J_20191224BC_A_J_20191225BC_A_J_20191226BC_A_J_20191227BC_A_J_20191228BC_A_J_20191229BC_A_J_20191230BC_A_J_20191231BC_A_J_20200101BC_A_J_20200102BC_A_J_20200103BC_A_J_20200104BC_A_J_20200105BC_A_J_20200106BC_A_J_20200107BC_A_J_20200108BC_A_J_20200109BC_A_J_20200110BC_A_J_20200111BC_A_J_20200112BC_A_J_20200113BC_A_J_20200114BC_A_J_20200115BC_A_J_20200116BC_A_J_20200117BC_A_J_20200118BC_A_J_20200119BC_A_J_20200120BC_A_J_20200121BC_A_J_20200122BC_A_J_20200123BC_A_J_20200124BC_A_J_20200125BC_A_J_20200126BC_A_J_20200127BC_A_J_20200128BC_A_J_20200129BC_A_J_20200130BC_A_J_20200131BC_A_J_20200201BC_A_J_20200202BC_A_J_20200203BC_A_J_20200204BC_A_J_20200205BC_A_J_20200206BC_A_J_20200207BC_A_J_20200208BC_A_J_20200209BC_A_J_20200210BC_A_J_20200211BC_A_J_20200212BC_A_J_20200213BC_A_J_20200214BC_A_J_20200215BC_A_J_20200216BC_A_J_20200217BC_A_J_20200218BC_A_J_20200219BC_A_J_20200220BC_A_J_20200221BC_A_J_20200222BC_A_J_20200223BC_A_J_20200224BC_A_J_20200225BC_A_J_20200226BC_A_J_20200227BC_A_J_20200228BC_A_J_20200229BC_A_J_20200301BC_A_J_20200302BC_A_J_20200303BC_A_J_20200304BC_A_J_20200305BC_A_J_20200306BC_A_J_20200307BC_A_J_20200308BC_A_J_20200309BC_A_J_20200310BC_A_J_20200311BC_A_J_20200312BC_A_J_20200313BC_A_J_20200314BC_A_J_20200315BC_A_J_20200316BC_A_J_20200317BC_A_J_20200318BC_A_J_20200319BC_A_J_20200320BC_A_J_20200321BC_A_J_20200322BC_A_J_20200323BC_A_J_20200324BC_A_J_20200325BC_A_J_20200326BC_A_J_20200327BC_A_J_20200328BC_A_J_20200329BC_A_J_20200330BC_A_J_20200331BC_A_J_20200401BC_A_J_20200402BC_A_J_20200403BC_A_J_20200404BC_A_J_20200405BC_A_J_20200406BC_A_J_20200407BC_A_J_20200408BC_A_J_20200409BC_A_J_20200410BC_A_J_20200411BC_A_J_20200412BC_A_J_20200413BC_A_J_20200414BC_A_J_20200415BC_A_J_20200416BC_A_J_20200417BC_A_J_20200418BC_A_J_20200419BC_A_J_20200420BC_A_J_20200421BC_A_J_20200422BC_A_J_20200423BC_A_J_20200424BC_A_J_20200425BC_A_J_20200426BC_A_J_20200427BC_A_J_20200428BC_A_J_20200429BC_A_J_20200430BC_A_J_20200501BC_A_J_20200502BC_A_J_20200503BC_A_J_20200504BC_A_J_20200505BC_A_J_20200506BC_A_J_20200507BC_A_J_20200508BC_A_J_20200509BC_A_J_20200510BC_A_J_20200511BC_A_J_20200512BC_A_J_20200513BC_A_J_20200514BC_A_J_20200515BC_A_J_20200516BC_A_J_20200517BC_A_J_20200518BC_A_J_20200519BC_A_J_20200520BC_A_J_20200521BC_A_J_20200522BC_A_J_20200523BC_A_J_20200524BC_A_J_20200525BC_A_J_20200526BC_A_J_20200527BC_A_J_20200528BC_A_J_20200529BC_A_J_20200530BC_A_J_20200531BC_A_J_20200601BC_A_J_20200602BC_A_J_20200603BC_A_J_20200604BC_A_J_20200605BC_A_J_20200606BC_A_J_20200607BC_A_J_20200608BC_A_J_20200609BC_A_J_20200610BC_A_J_20200611BC_A_J_20200612BC_A_J_20200613BC_A_J_20200614BC_A_J_20200615BC_A_J_20200616BC_A_J_20200617BC_A_J_20200618BC_A_J_20200619BC_A_J_20200620BC_A_J_20200621BC_A_J_20200622BC_A_J_20200623BC_A_J_20200624BC_A_J_20200625BC_A_J_20200626BC_A_J_20200627BC_A_J_20200628BC_A_J_20200629BC_A_J_20200630BC_A_J_20200701BC_A_J_20200702BC_A_J_20200703BC_A_J_20200704BC_A_J_20200705BC_A_J_20200706BC_A_J_20200707BC_A_J_20200708BC_A_J_20200709BC_A_J_20200710BC_A_J_20200711BC_A_J_20200712BC_A_J_20200713BC_A_J_20200714BC_A_J_20200715BC_A_J_20200716BC_A_J_20200717BC_A_J_20200718BC_A_J_20200719BC_A_J_20200720BC_A_J_20200721BC_A_J_20200722BC_A_J_20200723BC_A_J_20200724BC_A_J_20200725BC_A_J_20200726BC_A_J_20200727BC_A_J_20200728BC_A_J_20200729BC_A_J_20200730BC_A_J_20200731BC_A_J_20200801BC_A_J_20200802BC_A_J_20200803BC_A_J_20200804BC_A_J_20200805BC_A_J_20200806BC_A_J_20200807BC_A_J_20200808BC_A_J_20200809BC_A_J_20200810BC_A_J_20200811BC_A_J_20200812BC_A_J_20200813BC_A_J_20200814BC_A_J_20200815BC_A_J_20200816BC_A_J_20200817BC_A_J_20200818BC_A_J_20200819BC_A_J_20200820BC_A_J_20200821BC_A_J_20200822BC_A_J_20200823BC_A_J_20200824BC_A_J_20200825BC_A_J_20200826BC_A_J_20200827BC_A_J_20200828BC_A_J_20200829BC_A_J_20200830BC_A_J_20200831BC_A_J_20200901BC_A_J_20200902BC_A_J_20200903BC_A_J_20200904BC_A_J_20200905BC_A_J_20200906BC_A_J_20200907BC_A_J_20200908BC_A_J_20200909BC_A_J_20200910BC_A_J_20200911BC_A_J_20200912BC_A_J_20200913BC_A_J_20200914BC_A_J_20200915BC_A_J_20200916BC_A_J_20200917BC_A_J_20200918BC_A_J_20200919BC_A_J_20200920BC_A_J_20200921BC_A_J_20200922BC_A_J_20200923BC_A_J_20200924BC_A_J_20200925BC_A_J_20200926BC_A_J_20200927BC_A_J_20200928BC_A_J_20200929BC_A_J_20200930BC_A_J_20201001BC_A_J_20201002BC_A_J_20201003BC_A_J_20201004BC_A_J_20201005BC_A_J_20201006BC_A_J_20201007BC_A_J_20201008BC_A_J_20201009BC_A_J_20201010BC_A_J_20201011BC_A_J_20201012BC_A_J_20201013BC_A_J_20201014BC_A_J_20201015BC_A_J_20201016BC_A_J_20201017BC_A_J_20201018BC_A_J_20201019BC_A_J_20201020BC_A_J_20201021BC_A_J_20201022BC_A_J_20201023BC_A_J_20201024BC_A_J_20201025BC_A_J_20201026BC_A_J_20201027BC_A_J_20201028BC_A_J_20201029BC_A_J_20201030BC_A_J_20201031BC_A_J_20201101BC_A_J_20201102BC_A_J_20201103BC_A_J_20201104BC_A_J_20201105BC_A_J_20201106BC_A_J_20201107BC_A_J_20201108BC_A_J_20201109BC_A_J_20201110BC_A_J_20201111BC_A_J_20201112BC_A_J_20201113BC_A_J_20201114BC_A_J_20201115BC_A_J_20201116BC_A_J_20201117BC_A_J_20201118BC_A_J_20201119BC_A_J_20201120BC_A_J_20201121BC_A_J_20201122BC_A_J_20201123BC_A_J_20201124BC_A_J_20201125BC_A_J_20201126BC_A_J_20201127BC_A_J_20201128BC_A_J_20201129BC_A_J_20201130BC_A_J_20201201BC_A_J_20201202BC_A_J_20201203BC_A_J_20201204BC_A_J_20201205BC_A_J_20201206BC_A_J_20201207BC_A_J_20201208BC_A_J_20201209BC_A_J_20201210BC_A_J_20201211BC_A_J_20201212BC_A_J_20201213BC_A_J_20201214BC_A_J_20201215BC_A_J_20201216BC_A_J_20201217BC_A_J_20201218BC_A_J_20201219BC_A_J_20201220BC_A_J_20201221BC_A_J_20201222BC_A_J_20201223BC_A_J_20201224BC_A_J_20201225BC_A_J_20201226BC_A_J_20201227BC_A_J_20201228BC_A_J_20201229BC_A_J_20201230BC_A_J_20201231BC_A_J_20210101BC_A_J_20210102BC_A_J_20210103BC_A_J_20210104BC_A_J_20210105BC_A_J_20210106BC_A_J_20210107BC_A_J_20210108BC_A_J_20210109BC_A_J_20210110BC_A_J_20210111BC_A_J_20210112BC_A_J_20210113BC_A_J_20210114BC_A_J_20210115BC_A_J_20210116BC_A_J_20210117BC_A_J_20210118BC_A_J_20210119BC_A_J_20210120BC_A_J_20210121BC_A_J_20210122BC_A_J_20210123BC_A_J_20210124BC_A_J_20210125BC_A_J_20210126BC_A_J_20210127BC_A_J_20210128BC_A_J_20210129BC_A_J_20210130BC_A_J_20210131BC_A_J_20210201BC_A_J_20210202BC_A_J_20210203BC_A_J_20210204BC_A_J_20210205BC_A_J_20210206BC_A_J_20210207BC_A_J_20210208BC_A_J_20210209BC_A_J_20210210BC_A_J_20210211BC_A_J_20210212BC_A_J_20210213BC_A_J_20210214BC_A_J_20210215BC_A_J_20210216BC_A_J_20210217BC_A_J_20210218BC_A_J_20210219BC_A_J_20210220BC_A_J_20210221BC_A_J_20210222BC_A_J_20210223BC_A_J_20210224BC_A_J_20210225BC_A_J_20210226BC_A_J_20210227BC_A_J_20210228BC_A_J_20210301BC_A_J_20210302BC_A_J_20210303BC_A_J_20210304BC_A_J_20210305BC_A_J_20210306BC_A_J_20210307BC_A_J_20210308BC_A_J_20210309BC_A_J_20210310BC_A_J_20210311BC_A_J_20210312BC_A_J_20210313BC_A_J_20210314BC_A_J_20210315BC_A_J_20210316BC_A_J_20210317BC_A_J_20210318BC_A_J_20210319BC_A_J_20210320BC_A_J_20210321BC_A_J_20210322BC_A_J_20210323BC_A_J_20210324BC_A_J_20210325BC_A_J_20210326BC_A_J_20210327BC_A_J_20210328BC_A_J_20210329BC_A_J_20210330BC_A_J_20210331BC_A_J_20210401BC_A_J_20210402BC_A_J_20210403BC_A_J_20210404BC_A_J_20210405BC_A_J_20210406BC_A_J_20210407BC_A_J_20210408BC_A_J_20210409BC_A_J_20210410BC_A_J_20210411BC_A_J_20210412BC_A_J_20210413BC_A_J_20210414BC_A_J_20210415BC_A_J_20210416BC_A_J_20210417BC_A_J_20210418BC_A_J_20210419BC_A_J_20210420BC_A_J_20210421BC_A_J_20210422BC_A_J_20210423BC_A_J_20210424BC_A_J_20210425BC_A_J_20210426BC_A_J_20210427BC_A_J_20210428BC_A_J_20210429BC_A_J_20210430BC_A_J_20210501BC_A_J_20210502BC_A_J_20210503BC_A_J_20210504BC_A_J_20210505BC_A_J_20210506BC_A_J_20210507BC_A_J_20210508BC_A_J_20210509BC_A_J_20210510BC_A_J_20210511BC_A_J_20210512BC_A_J_20210513BC_A_J_20210514BC_A_J_20210515BC_A_J_20210516BC_A_J_20210517BC_A_J_20210518BC_A_J_20210519BC_A_J_20210520BC_A_J_20210521BC_A_J_20210522BC_A_J_20210523BC_A_J_20210524BC_A_J_20210525BC_A_J_20210526BC_A_J_20210527BC_A_J_20210528BC_A_J_20210529BC_A_J_20210530BC_A_J_20210531BC_A_J_20210601BC_A_J_20210602BC_A_J_20210603BC_A_J_20210604BC_A_J_20210605BC_A_J_20210606BC_A_J_20210607BC_A_J_20210608BC_A_J_20210609BC_A_J_20210610BC_A_J_20210611BC_A_J_20210612BC_A_J_20210613BC_A_J_20210614BC_A_J_20210615BC_A_J_20210616BC_A_J_20210617BC_A_J_20210618BC_A_J_20210619BC_A_J_20210620BC_A_J_20210621BC_A_J_20210622BC_A_J_20210623BC_A_J_20210624BC_A_J_20210625BC_A_J_20210626BC_A_J_20210627BC_A_J_20210628BC_A_J_20210629BC_A_J_20210630BC_A_J_20210701BC_A_J_20210702BC_A_J_20210703BC_A_J_20210704BC_A_J_20210705BC_A_J_20210706BC_A_J_20210707BC_A_J_20210708BC_A_J_20210709BC_A_J_20210710BC_A_J_20210711BC_A_J_20210712BC_A_J_20210713BC_A_J_20210714BC_A_J_20210715BC_A_J_20210716BC_A_J_20210717BC_A_J_20210718BC_A_J_20210719BC_A_J_20210720BC_A_J_20210721BC_A_J_20210722BC_A_J_20210723BC_A_J_20210724BC_A_J_20210725BC_A_J_20210726BC_A_J_20210727BC_A_J_20210728BC_A_J_20210729BC_A_J_20210730BC_A_J_20210731BC_A_J_20210801BC_A_J_20210802BC_A_J_20210803BC_A_J_20210804BC_A_J_20210805BC_A_J_20210806BC_A_J_20210807BC_A_J_20210808BC_A_J_20210809BC_A_J_20210810BC_A_J_20210811BC_A_J_20210812BC_A_J_20210813BC_A_J_20210814BC_A_J_20210815BC_A_J_20210816BC_A_J_20210817BC_A_J_20210818BC_A_J_20210819BC_A_J_20210820BC_A_J_20210821BC_A_J_20210822BC_A_J_20210823BC_A_J_20210824BC_A_J_20210825BC_A_J_20210826BC_A_J_20210827BC_A_J_20210828BC_A_J_20210829BC_A_J_20210830BC_A_J_20210831BC_A_J_20210901BC_A_J_20210902BC_A_J_20210903BC_A_J_20210904BC_A_J_20210905BC_A_J_20210906BC_A_J_20210907BC_A_J_20210908BC_A_J_20210909BC_A_J_20210910BC_A_J_20210911BC_A_J_20210912BC_A_J_20210913BC_A_J_20210914BC_A_J_20210915BC_A_J_20210916BC_A_J_20210917BC_A_J_20210918BC_A_J_20210919BC_A_J_20210920BC_A_J_20210921BC_A_J_20210922BC_A_J_20210923BC_A_J_20210924BC_A_J_20210925BC_A_J_20210926BC_A_J_20210927BC_A_J_20210928BC_A_J_20210929BC_A_J_20210930BC_A_J_20211001BC_A_J_20211002BC_A_J_20211003BC_A_J_20211004BC_A_J_20211005BC_A_J_20211006BC_A_J_20211007BC_A_J_20211008BC_A_J_20211009BC_A_J_20211010BC_A_J_20211011BC_A_J_20211012BC_A_J_20211013BC_A_J_20211014BC_A_J_20211015BC_A_J_20211016BC_A_J_20211017BC_A_J_20211018BC_A_J_20211019BC_A_J_20211020BC_A_J_20211021BC_A_J_20211022BC_A_J_20211023BC_A_J_20211024BC_A_J_20211025BC_A_J_20211026BC_A_J_20211027BC_A_J_20211028BC_A_J_20211029BC_A_J_20211030BC_A_J_20211031BC_A_J_20211101BC_A_J_20211102BC_A_J_20211103BC_A_J_20211104BC_A_J_20211105BC_A_J_20211106BC_A_J_20211107BC_A_J_20211108BC_A_J_20211109BC_A_J_20211110BC_A_J_20211111BC_A_J_20211112BC_A_J_20211113BC_A_J_20211114BC_A_J_20211115BC_A_J_20211116BC_A_J_20211117BC_A_J_20211118BC_A_J_20211119BC_A_J_20211120BC_A_J_20211121BC_A_J_20211122BC_A_J_20211123BC_A_J_20211124BC_A_J_20211125BC_A_J_20211126BC_A_J_20211127BC_A_J_20211128BC_A_J_20211129BC_A_J_20211130BC_A_J_20211201BC_A_J_20211202BC_A_J_20211203BC_A_J_20211204BC_A_J_20211205BC_A_J_20211206BC_A_J_20211207BC_A_J_20211208BC_A_J_20211209BC_A_J_20211210BC_A_J_20211211BC_A_J_20211212BC_A_J_20211213BC_A_J_20211214BC_A_J_20211215BC_A_J_20211216BC_A_J_20211217BC_A_J_20211218BC_A_J_20211219BC_A_J_20211220BC_A_J_20211221BC_A_J_20211222BC_A_J_20211223BC_A_J_20211224BC_A_J_20211225BC_A_J_20211226BC_A_J_20211227BC_A_J_20211228BC_A_J_20211229BC_A_J_20211230BC_A_J_20211231BC_A_J_20220101BC_A_J_20220102BC_A_J_20220103BC_A_J_20220104BC_A_J_20220105BC_A_J_20220106BC_A_J_20220107BC_A_J_20220108BC_A_J_20220109BC_A_J_20220110BC_A_J_20220111BC_A_J_20220112BC_A_J_20220113BC_A_J_20220114BC_A_J_20220115BC_A_J_20220116BC_A_J_20220117BC_A_J_20220118BC_A_J_20220119BC_A_J_20220120BC_A_J_20220121BC_A_J_20220122BC_A_J_20220123BC_A_J_20220124BC_A_J_20220125BC_A_J_20220126BC_A_J_20220127BC_A_J_20220128BC_A_J_20220129BC_A_J_20220130BC_A_J_20220131BC_A_J_20220201BC_A_J_20220202BC_A_J_20220203BC_A_J_20220204BC_A_J_20220205BC_A_J_20220206BC_A_J_20220207BC_A_J_20220208BC_A_J_20220209BC_A_J_20220210BC_A_J_20220211BC_A_J_20220212BC_A_J_20220213BC_A_J_20220214BC_A_J_20220215BC_A_J_20220216BC_A_J_20220217BC_A_J_20220218BC_A_J_20220219BC_A_J_20220220BC_A_J_20220221BC_A_J_20220222BC_A_J_20220223BC_A_J_20220224BC_A_J_20220225BC_A_J_20220226BC_A_J_20220227BC_A_J_20220228BC_A_J_20220301BC_A_J_20220302BC_A_J_20220303BC_A_J_20220304BC_A_J_20220305BC_A_J_20220306BC_A_J_20220307BC_A_J_20220308BC_A_J_20220309BC_A_J_20220310BC_A_J_20220311BC_A_J_20220312BC_A_J_20220313BC_A_J_20220314BC_A_J_20220315BC_A_J_20220316BC_A_J_20220317BC_A_J_20220318BC_A_J_20220319BC_A_J_20220320BC_A_J_20220321BC_A_J_20220322BC_A_J_20220323BC_A_J_20220324BC_A_J_20220325BC_A_J_20220326BC_A_J_20220327BC_A_J_20220328BC_A_J_20220329BC_A_J_20220330BC_A_J_20220331BC_A_J_20220401BC_A_J_20220402BC_A_J_20220403BC_A_J_20220404BC_A_J_20220405BC_A_J_20220406BC_A_J_20220407BC_A_J_20220408BC_A_J_20220409BC_A_J_20220410BC_A_J_20220411BC_A_J_20220412BC_A_J_20220413BC_A_J_20220414BC_A_J_20220415BC_A_J_20220416BC_A_J_20220417BC_A_J_20220418BC_A_J_20220419BC_A_J_20220420BC_A_J_20220421BC_A_J_20220422BC_A_J_20220423BC_A_J_20220424BC_A_J_20220425BC_A_J_20220426BC_A_J_20220427BC_A_J_20220428BC_A_J_20220429BC_A_J_20220430BC_A_J_20220501BC_A_J_20220502BC_A_J_20220503BC_A_J_20220504BC_A_J_20220505BC_A_J_20220506BC_A_J_20220507BC_A_J_20220508BC_A_J_20220509BC_A_J_20220510BC_A_J_20220511BC_A_J_20220512BC_A_J_20220513BC_A_J_20220514BC_A_J_20220515BC_A_J_20220516BC_A_J_20220517BC_A_J_20220518BC_A_J_20220519BC_A_J_20220520BC_A_J_20220521BC_A_J_20220522BC_A_J_20220523BC_A_J_20220524BC_A_J_20220525BC_A_J_20220526BC_A_J_20220527BC_A_J_20220528BC_A_J_20220529BC_A_J_20220530BC_A_J_20220531BC_A_J_20220601BC_A_J_20220602BC_A_J_20220603BC_A_J_20220604BC_A_J_20220605BC_A_J_20220606BC_A_J_20220607BC_A_J_20220608BC_A_J_20220609BC_A_J_20220610BC_A_J_20220611BC_A_J_20220612BC_A_J_20220613BC_A_J_20220614BC_A_J_20220615BC_A_J_20220616BC_A_J_20220617BC_A_J_20220618BC_A_J_20220619BC_A_J_20220620BC_A_J_20220621BC_A_J_20220622BC_A_J_20220623BC_A_J_20220624BC_A_J_20220625BC_A_J_20220626BC_A_J_20220627BC_A_J_20220628BC_A_J_20220629BC_A_J_20220630BC_A_J_20220701BC_A_J_20220702BC_A_J_20220703BC_A_J_20220704BC_A_J_20220705BC_A_J_20220706BC_A_J_20220707BC_A_J_20220708BC_A_J_20220709BC_A_J_20220710BC_A_J_20220711BC_A_J_20220712BC_A_J_20220713BC_A_J_20220714BC_A_J_20220715BC_A_J_20220716BC_A_J_20220717BC_A_J_20220718BC_A_J_20220719BC_A_J_20220720BC_A_J_20220721BC_A_J_20220722BC_A_J_20220723BC_A_J_20220724BC_A_J_20220725BC_A_J_20220726BC_A_J_20220727BC_A_J_20220728BC_A_J_20220729BC_A_J_20220730BC_A_J_20220731BC_A_J_20220801BC_A_J_20220802BC_A_J_20220803BC_A_J_20220804BC_A_J_20220805BC_A_J_20220806BC_A_J_20220807BC_A_J_20220808BC_A_J_20220809BC_A_J_20220810BC_A_J_20220811BC_A_J_20220812BC_A_J_20220813BC_A_J_20220814BC_A_J_20220815BC_A_J_20220816BC_A_J_20220817BC_A_J_20220818BC_A_J_20220819BC_A_J_20220820BC_A_J_20220821BC_A_J_20220822BC_A_J_20220823BC_A_J_20220824BC_A_J_20220825BC_A_J_20220826BC_A_J_20220827BC_A_J_20220828BC_A_J_20220829BC_A_J_20220830BC_A_J_20220831BC_A_J_20220901BC_A_J_20220902BC_A_J_20220903BC_A_J_20220904BC_A_J_20220905BC_A_J_20220906BC_A_J_20220907BC_A_J_20220908BC_A_J_20220909BC_A_J_20220910BC_A_J_20220911BC_A_J_20220912BC_A_J_20220913BC_A_J_20220914BC_A_J_20220915BC_A_J_20220916BC_A_J_20220917BC_A_J_20220918BC_A_J_20220919BC_A_J_20220920BC_A_J_20220921BC_A_J_20220922BC_A_J_20220923BC_A_J_20220924BC_A_J_20220925BC_A_J_20220926BC_A_J_20220927BC_A_J_20220928BC_A_J_20220929BC_A_J_20220930BC_A_J_20221001BC_A_J_20221002BC_A_J_20221003BC_A_J_20221004BC_A_J_20221005BC_A_J_20221006BC_A_J_20221007BC_A_J_20221008BC_A_J_20221009BC_A_J_20221010BC_A_J_20221011BC_A_J_20221012BC_A_J_20221013BC_A_J_20221014BC_A_J_20221015BC_A_J_20221016BC_A_J_20221017BC_A_J_20221018BC_A_J_20221019BC_A_J_20221020BC_A_J_20221021BC_A_J_20221022BC_A_J_20221023BC_A_J_20221024BC_A_J_20221025BC_A_J_20221026BC_A_J_20221027BC_A_J_20221028BC_A_J_20221029BC_A_J_20221030BC_A_J_20221031BC_A_J_20221101BC_A_J_20221102BC_A_J_20221103BC_A_J_20221104BC_A_J_20221105BC_A_J_20221106BC_A_J_20221107BC_A_J_20221108BC_A_J_20221109BC_A_J_20221110BC_A_J_20221111BC_A_J_20221112BC_A_J_20221113BC_A_J_20221114BC_A_J_20221115BC_A_J_20221116BC_A_J_20221117BC_A_J_20221118BC_A_J_20221119BC_A_J_20221120BC_A_J_20221121BC_A_J_20221122BC_A_J_20221123BC_A_J_20221124BC_A_J_20221125BC_A_J_20221126BC_A_J_20221127BC_A_J_20221128BC_A_J_20221129BC_A_J_20221130BC_A_J_20221201BC_A_J_20221202BC_A_J_20221203BC_A_J_20221204BC_A_J_20221205BC_A_J_20221206BC_A_J_20221207BC_A_J_20221208BC_A_J_20221209BC_A_J_20221210BC_A_J_20221211BC_A_J_20221212BC_A_J_20221213BC_A_J_20221214BC_A_J_20221215BC_A_J_20221216BC_A_J_20221217BC_A_J_20221218BC_A_J_20221219BC_A_J_20221220BC_A_J_20221221BC_A_J_20221222BC_A_J_20221223BC_A_J_20221224BC_A_J_20221225BC_A_J_20221226BC_A_J_20221227BC_A_J_20221228BC_A_J_20221229BC_A_J_20221230BC_A_J_20221231BC_A_J_20230101BC_A_J_20230102BC_A_J_20230103BC_A_J_20230104BC_A_J_20230105BC_A_J_20230106BC_A_J_20230107BC_A_J_20230108BC_A_J_20230109BC_A_J_20230110BC_A_J_20230111BC_A_J_20230112BC_A_J_20230113BC_A_J_20230114BC_A_J_20230115BC_A_J_20230116BC_A_J_20230117BC_A_J_20230118BC_A_J_20230119BC_A_J_20230120BC_A_J_20230121BC_A_J_20230122BC_A_J_20230123BC_A_J_20230124BC_A_J_20230125BC_A_J_20230126BC_A_J_20230127BC_A_J_20230128BC_A_J_20230129BC_A_J_20230130BC_A_J_20230131BC_A_J_20230201BC_A_J_20230202BC_A_J_20230203BC_A_J_20230204BC_A_J_20230205BC_A_J_20230206BC_A_J_20230207BC_A_J_20230208BC_A_J_20230209BC_A_J_20230210BC_A_J_20230211BC_A_J_20230212BC_A_J_20230213BC_A_J_20230214BC_A_J_20230215BC_A_J_20230216BC_A_J_20230217BC_A_J_20230218BC_A_J_20230219BC_A_J_20230220BC_A_J_20230221BC_A_J_20230222BC_A_J_20230223BC_A_J_20230224BC_A_J_20230225BC_A_J_20230226BC_A_J_20230227BC_A_J_20230228BC_A_J_20230301BC_A_J_20230302BC_A_J_20230303' to numeric

## Preprocessing
### 범주형 변수 : one-hot encoding
### 연속형 변수 : min-max scaling

In [31]:
# A = pd.get_dummies(A, columns=['corporation'])

# # 'Col5' 열 (J, S)을 one-hot 인코딩
# A = pd.get_dummies(A, columns=['location'])

In [80]:
A.head()

ID   timestamp item corporation location  supply(kg)  \
0  TG_A_J_20190101  2019-01-01   TG           A        J         0.0   
1  TG_A_J_20190102  2019-01-02   TG           A        J         0.0   
2  TG_A_J_20190103  2019-01-03   TG           A        J     60601.0   
3  TG_A_J_20190104  2019-01-04   TG           A        J     25000.0   
4  TG_A_J_20190105  2019-01-05   TG           A        J     32352.0   

   price(원/kg)  
0          0.0  
1          0.0  
2       1728.0  
3       1408.0  
4       1250.0

In [81]:
from sklearn.preprocessing import MinMaxScaler

# Input scale
scaler_x = MinMaxScaler()
scaler_x.fit(A['supply(kg)'].values.reshape(-1,1))
A['supply(kg)'] = scaler_x.fit_transform(A['supply(kg)'].values.reshape(-1,1))


# Input scale
scaler_y = MinMaxScaler()
scaler_y.fit(A['price(원/kg)'].values.reshape(-1,1))
A['price(원/kg)'] = scaler_x.fit_transform(A['price(원/kg)'].values.reshape(-1,1))



/var/folders/6r/w8k58h7j3799_jkwn2c_nk7c0000gn/T/ipykernel_41214/4100278134.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['supply(kg)'] = scaler_x.fit_transform(A['supply(kg)'].values.reshape(-1,1))
/var/folders/6r/w8k58h7j3799_jkwn2c_nk7c0000gn/T/ipykernel_41214/4100278134.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['price(원/kg)'] = scaler_x.fit_transform(A['price(원/kg)'].values.reshape(-1,1))


In [82]:
A['timestamp'] = pd.to_datetime(A['timestamp'])

/var/folders/6r/w8k58h7j3799_jkwn2c_nk7c0000gn/T/ipykernel_41214/2994222738.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['timestamp'] = pd.to_datetime(A['timestamp'])


In [83]:
A.head()

ID  timestamp item corporation location  supply(kg)  \
0  TG_A_J_20190101 2019-01-01   TG           A        J    0.000000   
1  TG_A_J_20190102 2019-01-02   TG           A        J    0.000000   
2  TG_A_J_20190103 2019-01-03   TG           A        J    0.223491   
3  TG_A_J_20190104 2019-01-04   TG           A        J    0.092198   
4  TG_A_J_20190105 2019-01-05   TG           A        J    0.119311   

   price(원/kg)  
0     0.000000  
1     0.000000  
2     0.082644  
3     0.067339  
4     0.059783

In [84]:
for i in range(0,15230,1523):
    TG

0 1523
1523 3046
3046 4569
4569 6092
6092 7615
7615 9138
9138 10661
10661 12184
12184 13707
13707 15230


In [72]:
# 'timestamp' 열을 기준으로 데이터프레임을 그룹화
grouped = A.groupby('timestamp')

# 각 그룹을 2차원 배열로 변환
A_array_list = []
for _, group in grouped:
    # print(group)
    group_array = group.values[:, 3:].astype(np.float32)  # 3번째 열부터 끝까지 선택하고 실수형으로 변환
    A_array_list.append(group_array)

# 결과 확인
for array in A_array_list:
    print(array)

[[0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1.]]
[[0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1.]]
[[0.22349128 0.08264384 1.         0.         0.         0.
  0.         1.         0.        ]
 [0.7028832  0.12080922 1.         0.         0.         0.
  0.         0.         1.        ]
 [0.0948052  0.08092209 0.         1.         0.         0.
  0.         1.         0.        ]
 [0.41539925 0.09297432 0.         1.         0.         0.
  0.         0.         1.        ]
 [0.18153019 0

## Train-Valid split

In [73]:
len(A_array_list)

1523

AttributeError: 'list' object has no attribute 'reshape'

In [1]:
import pandas as pd
import numpy as np

# 주어진 넘파이 배열
my_array = np.array([[2, 3], [4, 5]])

# 넘파이 배열을 데이터프레임으로 변환
df = pd.DataFrame({'Column1': my_array[:, 0], 'Column2': my_array[:, 1]})

# 데이터프레임 출력
print(df)


   Column1  Column2
0        2        3
1        4        5
